"""
Report generation for aggregated reconnaissance results.
Supports HTML and Markdown formats.
"""

import json
from datetime import datetime
from pathlib import Path
from typing import List, Dict, Any

def generate_markdown_report(target: str, results: List[Dict[str, Any]]) -> str:
    """Generate a Markdown report from a list of scan results."""
    lines = []
    lines.append(f"# Reconnaissance Report: {target}")
    lines.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append("")
    lines.append("## Summary")
    lines.append(f"Total scans performed: {len(results)}")
    lines.append("")

    for idx, res in enumerate(results, 1):
        lines.append(f"## Scan {idx}: {res['module']} ({res['profile']})")
        lines.append(f"**Timestamp:** {res['timestamp']}")
        lines.append("")
        lines.append("### Parsed Intelligence")
        if isinstance(res['parsed'], dict):
            for k, v in res['parsed'].items():
                if k == 'raw_output':
                    continue
                lines.append(f"- **{k}:** {v}")
        else:
            lines.append(str(res['parsed']))
        lines.append("")
        lines.append("### Raw Output (stdout)")
        lines.append("```")
        lines.append(res['stdout'] or "(no output)")
        lines.append("```")
        if res['stderr']:
            lines.append("### Standard Error")
            lines.append("```")
            lines.append(res['stderr'])
            lines.append("```")
        lines.append("---")
        lines.append("")

    return "\n".join(lines)


def generate_html_report(target: str, results: List[Dict[str, Any]]) -> str:
    """Generate a styled HTML report."""
    html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Recon Report: {target}</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 20px; background: #f5f5f5; }}
        h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; }}
        h2 {{ color: #34495e; margin-top: 30px; }}
        h3 {{ color: #2980b9; }}
        .summary {{ background: #ecf0f1; padding: 10px; border-radius: 5px; }}
        .scan {{ background: white; padding: 15px; margin: 20px 0; border-radius: 5px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }}
        .parsed {{ background: #e8f6f3; padding: 10px; border-left: 4px solid #1abc9c; }}
        .raw {{ background: #fcf3e8; padding: 10px; border-left: 4px solid #f39c12; font-family: monospace; white-space: pre-wrap; }}
        .error {{ background: #f9ebea; border-left: 4px solid #e74c3c; }}
        footer {{ margin-top: 30px; font-size: 0.9em; color: #7f8c8d; text-align: center; }}
    </style>
</head>
<body>
    <h1>🔍 Reconnaissance Report: {target}</h1>
    <p><strong>Generated:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
    <div class="summary">
        <h2>Summary</h2>
        <p>Total scans performed: {len(results)}</p>
    </div>
"""
    for idx, res in enumerate(results, 1):
        html += f"""
    <div class="scan">
        <h3>Scan {idx}: {res['module']} ({res['profile']})</h3>
        <p><strong>Timestamp:</strong> {res['timestamp']}</p>
        <div class="parsed">
            <h4>Parsed Intelligence</h4>
"""
        if isinstance(res['parsed'], dict):
            for k, v in res['parsed'].items():
                if k == 'raw_output':
                    continue
                html += f"            <p><strong>{k}:</strong> {v}</p>\n"
        else:
            html += f"            <p>{res['parsed']}</p>\n"
        html += f"""        </div>
        <div class="raw">
            <h4>Raw Output (stdout)</h4>
            <pre>{res['stdout'] or '(no output)'}</pre>
        </div>
"""
        if res['stderr']:
            html += f"""        <div class="error">
            <h4>Standard Error</h4>
            <pre>{res['stderr']}</pre>
        </div>
"""
        html += "    </div>\n"

    html += """    <footer>Generated by recon-progressive</footer>
</body>
</html>"""
    return html


def save_report(target: str, results: List[Dict[str, Any]], format: str = "html") -> Path:
    """Generate and save report to file. Returns path to saved file."""
    out_dir = Path("recon-output")
    out_dir.mkdir(exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_target = target.replace('.', '_').replace('/', '_')
    filename = out_dir / f"report_{safe_target}_{timestamp}.{format}"

    if format == "html":
        content = generate_html_report(target, results)
    else:  # markdown
        content = generate_markdown_report(target, results)

    with open(filename, 'w', encoding='utf-8') as f:
        f.write(content)

    return filename